# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build"
  lane :build do
    cert
    sigh
    gym
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Deploy to testflight"
  lane :deploy do
    cert
    sigh
    gym(scheme: "nanozap")
    upload_to_testflight
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :test do
    run_tests(scheme: "nanozapTests")
  end
end
